/** MARD 221-color standard palette — static data only, never dynamic imports. */
export type MardColorCategory = "red" | "blue" | "green" | "yellow" | "brown" | "grayscale";
export type MardColorEntry = { id: string; name: string; hex: string; category: MardColorCategory };
export type UiColorFilter = "reds" | "blues" | "greens" | "yellows" | "browns" | "grayscale";
export const MARD_EXTENDED_PALETTE: MardColorEntry[] = [
  { id: "A1", name: "MARD A1", hex: "#FAF5CD", category: "yellow" },
  { id: "A2", name: "MARD A2", hex: "#FCFED6", category: "yellow" },
  { id: "A3", name: "MARD A3", hex: "#FCFF92", category: "yellow" },
  { id: "A4", name: "MARD A4", hex: "#F7EC5C", category: "yellow" },
  { id: "A5", name: "MARD A5", hex: "#F0D83A", category: "yellow" },
  { id: "A6", name: "MARD A6", hex: "#FDA951", category: "yellow" },
  { id: "A7", name: "MARD A7", hex: "#FA8C4F", category: "yellow" },
  { id: "A8", name: "MARD A8", hex: "#FBDA4D", category: "yellow" },
  { id: "A9", name: "MARD A9", hex: "#F79D5F", category: "yellow" },
  { id: "A10", name: "MARD A10", hex: "#F47E38", category: "yellow" },
  { id: "A11", name: "MARD A11", hex: "#FEDB99", category: "yellow" },
  { id: "A12", name: "MARD A12", hex: "#FDA276", category: "yellow" },
  { id: "A13", name: "MARD A13", hex: "#FEC667", category: "yellow" },
  { id: "A14", name: "MARD A14", hex: "#F75842", category: "yellow" },
  { id: "A15", name: "MARD A15", hex: "#FBF65E", category: "yellow" },
  { id: "A16", name: "MARD A16", hex: "#FEFF97", category: "yellow" },
  { id: "A17", name: "MARD A17", hex: "#FDE173", category: "yellow" },
  { id: "A18", name: "MARD A18", hex: "#FCBF80", category: "yellow" },
  { id: "A19", name: "MARD A19", hex: "#FD7E77", category: "yellow" },
  { id: "A20", name: "MARD A20", hex: "#F9D666", category: "yellow" },
  { id: "A21", name: "MARD A21", hex: "#FAE393", category: "yellow" },
  { id: "A22", name: "MARD A22", hex: "#EDF878", category: "yellow" },
  { id: "A23", name: "MARD A23", hex: "#E4C8BA", category: "yellow" },
  { id: "A24", name: "MARD A24", hex: "#F3F6A9", category: "yellow" },
  { id: "A25", name: "MARD A25", hex: "#FDF785", category: "yellow" },
  { id: "A26", name: "MARD A26", hex: "#FFC734", category: "yellow" },
  { id: "B1", name: "MARD B1", hex: "#DFF13B", category: "green" },
  { id: "B2", name: "MARD B2", hex: "#64F343", category: "green" },
  { id: "B3", name: "MARD B3", hex: "#A1F586", category: "green" },
  { id: "B4", name: "MARD B4", hex: "#5FDF34", category: "green" },
  { id: "B5", name: "MARD B5", hex: "#39E158", category: "green" },
  { id: "B6", name: "MARD B6", hex: "#64E0A4", category: "green" },
  { id: "B7", name: "MARD B7", hex: "#3EAE7C", category: "green" },
  { id: "B8", name: "MARD B8", hex: "#1D9B54", category: "green" },
  { id: "B9", name: "MARD B9", hex: "#2A5037", category: "green" },
  { id: "B10", name: "MARD B10", hex: "#9AD1BA", category: "green" },
  { id: "B11", name: "MARD B11", hex: "#627032", category: "green" },
  { id: "B12", name: "MARD B12", hex: "#1A6E3D", category: "green" },
  { id: "B13", name: "MARD B13", hex: "#C8E87D", category: "green" },
  { id: "B14", name: "MARD B14", hex: "#ABE84F", category: "green" },
  { id: "B15", name: "MARD B15", hex: "#305335", category: "green" },
  { id: "B16", name: "MARD B16", hex: "#C0ED9C", category: "green" },
  { id: "B17", name: "MARD B17", hex: "#9EB33E", category: "green" },
  { id: "B18", name: "MARD B18", hex: "#E6ED4F", category: "green" },
  { id: "B19", name: "MARD B19", hex: "#26B78E", category: "green" },
  { id: "B20", name: "MARD B20", hex: "#CBECCF", category: "green" },
  { id: "B21", name: "MARD B21", hex: "#18616A", category: "green" },
  { id: "B22", name: "MARD B22", hex: "#0A4241", category: "green" },
  { id: "B23", name: "MARD B23", hex: "#343B1A", category: "green" },
  { id: "B24", name: "MARD B24", hex: "#E8FAA6", category: "green" },
  { id: "B25", name: "MARD B25", hex: "#4E846D", category: "green" },
  { id: "B26", name: "MARD B26", hex: "#907C35", category: "green" },
  { id: "B27", name: "MARD B27", hex: "#D0E0AF", category: "green" },
  { id: "B28", name: "MARD B28", hex: "#9EE5BB", category: "green" },
  { id: "B29", name: "MARD B29", hex: "#C6DF5F", category: "green" },
  { id: "B30", name: "MARD B30", hex: "#E3FBB1", category: "green" },
  { id: "B31", name: "MARD B31", hex: "#B4E691", category: "green" },
  { id: "B32", name: "MARD B32", hex: "#92AD60", category: "green" },
  { id: "C1", name: "MARD C1", hex: "#F0FEE4", category: "blue" },
  { id: "C2", name: "MARD C2", hex: "#ABF8FE", category: "blue" },
  { id: "C3", name: "MARD C3", hex: "#A2E0F7", category: "blue" },
  { id: "C4", name: "MARD C4", hex: "#44CDFB", category: "blue" },
  { id: "C5", name: "MARD C5", hex: "#06AADF", category: "blue" },
  { id: "C6", name: "MARD C6", hex: "#54A7E9", category: "blue" },
  { id: "C7", name: "MARD C7", hex: "#3977CA", category: "blue" },
  { id: "C8", name: "MARD C8", hex: "#0F52BD", category: "blue" },
  { id: "C9", name: "MARD C9", hex: "#3349C3", category: "blue" },
  { id: "C10", name: "MARD C10", hex: "#3CBCE3", category: "blue" },
  { id: "C11", name: "MARD C11", hex: "#2ADED3", category: "blue" },
  { id: "C12", name: "MARD C12", hex: "#1E334E", category: "blue" },
  { id: "C13", name: "MARD C13", hex: "#CDE7FE", category: "blue" },
  { id: "C14", name: "MARD C14", hex: "#D5FCF7", category: "blue" },
  { id: "C15", name: "MARD C15", hex: "#21C5C4", category: "blue" },
  { id: "C16", name: "MARD C16", hex: "#1858A2", category: "blue" },
  { id: "C17", name: "MARD C17", hex: "#02D1F3", category: "blue" },
  { id: "C18", name: "MARD C18", hex: "#213244", category: "blue" },
  { id: "C19", name: "MARD C19", hex: "#18869D", category: "blue" },
  { id: "C20", name: "MARD C20", hex: "#1A70A9", category: "blue" },
  { id: "C21", name: "MARD C21", hex: "#BCDDFC", category: "blue" },
  { id: "C22", name: "MARD C22", hex: "#6BB1BB", category: "blue" },
  { id: "C23", name: "MARD C23", hex: "#C8E2FD", category: "blue" },
  { id: "C24", name: "MARD C24", hex: "#7EC5F9", category: "blue" },
  { id: "C25", name: "MARD C25", hex: "#A9E8E0", category: "blue" },
  { id: "C26", name: "MARD C26", hex: "#42ADCF", category: "blue" },
  { id: "C27", name: "MARD C27", hex: "#D0DEF9", category: "blue" },
  { id: "C28", name: "MARD C28", hex: "#BDCEE8", category: "blue" },
  { id: "C29", name: "MARD C29", hex: "#364A89", category: "blue" },
  { id: "D1", name: "MARD D1", hex: "#ACB7EF", category: "red" },
  { id: "D2", name: "MARD D2", hex: "#868DD3", category: "red" },
  { id: "D3", name: "MARD D3", hex: "#3554AF", category: "red" },
  { id: "D4", name: "MARD D4", hex: "#162D7B", category: "red" },
  { id: "D5", name: "MARD D5", hex: "#B34EC6", category: "red" },
  { id: "D6", name: "MARD D6", hex: "#B37BDC", category: "red" },
  { id: "D7", name: "MARD D7", hex: "#8758A9", category: "red" },
  { id: "D8", name: "MARD D8", hex: "#E3D2FE", category: "red" },
  { id: "D9", name: "MARD D9", hex: "#D5B9F4", category: "red" },
  { id: "D10", name: "MARD D10", hex: "#301A49", category: "red" },
  { id: "D11", name: "MARD D11", hex: "#BEB9E2", category: "red" },
  { id: "D12", name: "MARD D12", hex: "#DC99CE", category: "red" },
  { id: "D13", name: "MARD D13", hex: "#B5038D", category: "red" },
  { id: "D14", name: "MARD D14", hex: "#862993", category: "red" },
  { id: "D15", name: "MARD D15", hex: "#2F1F8C", category: "red" },
  { id: "D16", name: "MARD D16", hex: "#E2E4F0", category: "red" },
  { id: "D17", name: "MARD D17", hex: "#C7D3F9", category: "red" },
  { id: "D18", name: "MARD D18", hex: "#9A64B8", category: "red" },
  { id: "D19", name: "MARD D19", hex: "#D8C2D9", category: "red" },
  { id: "D20", name: "MARD D20", hex: "#9A35AD", category: "red" },
  { id: "D21", name: "MARD D21", hex: "#940595", category: "red" },
  { id: "D22", name: "MARD D22", hex: "#38389A", category: "red" },
  { id: "D23", name: "MARD D23", hex: "#EADBF8", category: "red" },
  { id: "D24", name: "MARD D24", hex: "#768AE1", category: "red" },
  { id: "D25", name: "MARD D25", hex: "#4950C2", category: "red" },
  { id: "D26", name: "MARD D26", hex: "#D6C6EB", category: "red" },
  { id: "E1", name: "MARD E1", hex: "#F6D4CB", category: "red" },
  { id: "E2", name: "MARD E2", hex: "#FCC1DD", category: "red" },
  { id: "E3", name: "MARD E3", hex: "#F6BDE8", category: "red" },
  { id: "E4", name: "MARD E4", hex: "#E8649E", category: "red" },
  { id: "E5", name: "MARD E5", hex: "#F0569F", category: "red" },
  { id: "E6", name: "MARD E6", hex: "#EB4172", category: "red" },
  { id: "E7", name: "MARD E7", hex: "#C53674", category: "red" },
  { id: "E8", name: "MARD E8", hex: "#FDDBE9", category: "red" },
  { id: "E9", name: "MARD E9", hex: "#E376C7", category: "red" },
  { id: "E10", name: "MARD E10", hex: "#D13B95", category: "red" },
  { id: "E11", name: "MARD E11", hex: "#F7DAD4", category: "red" },
  { id: "E12", name: "MARD E12", hex: "#F693BF", category: "red" },
  { id: "E13", name: "MARD E13", hex: "#B5026A", category: "red" },
  { id: "E14", name: "MARD E14", hex: "#FAD4BF", category: "red" },
  { id: "E15", name: "MARD E15", hex: "#F5C9CA", category: "red" },
  { id: "E16", name: "MARD E16", hex: "#FBF4EC", category: "red" },
  { id: "E17", name: "MARD E17", hex: "#F7E3EC", category: "red" },
  { id: "E18", name: "MARD E18", hex: "#F9C8DB", category: "red" },
  { id: "E19", name: "MARD E19", hex: "#F6BBD1", category: "red" },
  { id: "E20", name: "MARD E20", hex: "#D7C6CE", category: "red" },
  { id: "E21", name: "MARD E21", hex: "#C09DA4", category: "red" },
  { id: "E22", name: "MARD E22", hex: "#B38C9F", category: "red" },
  { id: "E23", name: "MARD E23", hex: "#937D8A", category: "red" },
  { id: "E24", name: "MARD E24", hex: "#DEBEE5", category: "red" },
  { id: "F1", name: "MARD F1", hex: "#FE9381", category: "red" },
  { id: "F2", name: "MARD F2", hex: "#F63D4B", category: "red" },
  { id: "F3", name: "MARD F3", hex: "#EE4E3E", category: "red" },
  { id: "F4", name: "MARD F4", hex: "#FB2A40", category: "red" },
  { id: "F5", name: "MARD F5", hex: "#E10328", category: "red" },
  { id: "F6", name: "MARD F6", hex: "#913635", category: "red" },
  { id: "F7", name: "MARD F7", hex: "#911932", category: "red" },
  { id: "F8", name: "MARD F8", hex: "#BB0126", category: "red" },
  { id: "F9", name: "MARD F9", hex: "#E0677A", category: "red" },
  { id: "F10", name: "MARD F10", hex: "#874628", category: "brown" },
  { id: "F11", name: "MARD F11", hex: "#592323", category: "brown" },
  { id: "F12", name: "MARD F12", hex: "#F3536B", category: "red" },
  { id: "F13", name: "MARD F13", hex: "#F45C45", category: "red" },
  { id: "F14", name: "MARD F14", hex: "#FCADB2", category: "red" },
  { id: "F15", name: "MARD F15", hex: "#D50527", category: "red" },
  { id: "F16", name: "MARD F16", hex: "#F8C0A9", category: "brown" },
  { id: "F17", name: "MARD F17", hex: "#E89B7D", category: "brown" },
  { id: "F18", name: "MARD F18", hex: "#D07F4A", category: "brown" },
  { id: "F19", name: "MARD F19", hex: "#BE454A", category: "red" },
  { id: "F20", name: "MARD F20", hex: "#C69495", category: "red" },
  { id: "F21", name: "MARD F21", hex: "#F2B8C6", category: "red" },
  { id: "F22", name: "MARD F22", hex: "#F7C3D0", category: "red" },
  { id: "F23", name: "MARD F23", hex: "#ED806C", category: "red" },
  { id: "F24", name: "MARD F24", hex: "#E09DAF", category: "red" },
  { id: "F25", name: "MARD F25", hex: "#E84854", category: "red" },
  { id: "G1", name: "MARD G1", hex: "#FFE4D3", category: "brown" },
  { id: "G2", name: "MARD G2", hex: "#FCC6AC", category: "brown" },
  { id: "G3", name: "MARD G3", hex: "#F1C4A5", category: "brown" },
  { id: "G4", name: "MARD G4", hex: "#DCB387", category: "brown" },
  { id: "G5", name: "MARD G5", hex: "#E7B34E", category: "brown" },
  { id: "G6", name: "MARD G6", hex: "#E3A014", category: "brown" },
  { id: "G7", name: "MARD G7", hex: "#985C3A", category: "brown" },
  { id: "G8", name: "MARD G8", hex: "#713D2F", category: "brown" },
  { id: "G9", name: "MARD G9", hex: "#E4B685", category: "brown" },
  { id: "G10", name: "MARD G10", hex: "#DA8C42", category: "brown" },
  { id: "G11", name: "MARD G11", hex: "#DAC898", category: "brown" },
  { id: "G12", name: "MARD G12", hex: "#FEC993", category: "brown" },
  { id: "G13", name: "MARD G13", hex: "#B2714B", category: "brown" },
  { id: "G14", name: "MARD G14", hex: "#8B684C", category: "brown" },
  { id: "G15", name: "MARD G15", hex: "#F6F8E3", category: "brown" },
  { id: "G16", name: "MARD G16", hex: "#F2D8C1", category: "brown" },
  { id: "G17", name: "MARD G17", hex: "#77544E", category: "brown" },
  { id: "G18", name: "MARD G18", hex: "#FFE3D5", category: "brown" },
  { id: "G19", name: "MARD G19", hex: "#DD7D41", category: "brown" },
  { id: "G20", name: "MARD G20", hex: "#A5452F", category: "brown" },
  { id: "G21", name: "MARD G21", hex: "#B38561", category: "brown" },
  { id: "H1", name: "MARD H1", hex: "#FFFFFF", category: "grayscale" },
  { id: "H2", name: "MARD H2", hex: "#FBFBFB", category: "grayscale" },
  { id: "H3", name: "MARD H3", hex: "#B4B4B4", category: "grayscale" },
  { id: "H4", name: "MARD H4", hex: "#878787", category: "grayscale" },
  { id: "H5", name: "MARD H5", hex: "#464648", category: "grayscale" },
  { id: "H6", name: "MARD H6", hex: "#2C2C2C", category: "grayscale" },
  { id: "H7", name: "MARD H7", hex: "#010101", category: "grayscale" },
  { id: "H8", name: "MARD H8", hex: "#E7D6DC", category: "grayscale" },
  { id: "H9", name: "MARD H9", hex: "#EFEDEE", category: "grayscale" },
  { id: "H10", name: "MARD H10", hex: "#EBEBEB", category: "grayscale" },
  { id: "H11", name: "MARD H11", hex: "#CDCDCD", category: "grayscale" },
  { id: "H12", name: "MARD H12", hex: "#FDF6EE", category: "grayscale" },
  { id: "H13", name: "MARD H13", hex: "#F4EDF1", category: "grayscale" },
  { id: "H14", name: "MARD H14", hex: "#CED7D4", category: "grayscale" },
  { id: "H15", name: "MARD H15", hex: "#9AA6A6", category: "grayscale" },
  { id: "H16", name: "MARD H16", hex: "#1B1213", category: "grayscale" },
  { id: "H17", name: "MARD H17", hex: "#F0EEEF", category: "grayscale" },
  { id: "H18", name: "MARD H18", hex: "#FCFFF6", category: "grayscale" },
  { id: "H19", name: "MARD H19", hex: "#F2EEE5", category: "grayscale" },
  { id: "H20", name: "MARD H20", hex: "#96A09F", category: "grayscale" },
  { id: "H21", name: "MARD H21", hex: "#F8FBE6", category: "grayscale" },
  { id: "H22", name: "MARD H22", hex: "#CACAD2", category: "grayscale" },
  { id: "H23", name: "MARD H23", hex: "#9B9C94", category: "grayscale" },
  { id: "M1", name: "MARD M1", hex: "#BBC6B6", category: "brown" },
  { id: "M2", name: "MARD M2", hex: "#909994", category: "grayscale" },
  { id: "M3", name: "MARD M3", hex: "#697E81", category: "grayscale" },
  { id: "M4", name: "MARD M4", hex: "#E0D4BC", category: "brown" },
  { id: "M5", name: "MARD M5", hex: "#D1CCAF", category: "brown" },
  { id: "M6", name: "MARD M6", hex: "#B0AA86", category: "brown" },
  { id: "M7", name: "MARD M7", hex: "#B0A796", category: "brown" },
  { id: "M8", name: "MARD M8", hex: "#AE8082", category: "brown" },
  { id: "M9", name: "MARD M9", hex: "#A68862", category: "brown" },
  { id: "M10", name: "MARD M10", hex: "#C4B3BB", category: "brown" },
  { id: "M11", name: "MARD M11", hex: "#9D7693", category: "brown" },
  { id: "M12", name: "MARD M12", hex: "#644B51", category: "brown" },
  { id: "M13", name: "MARD M13", hex: "#C79266", category: "brown" },
  { id: "M14", name: "MARD M14", hex: "#C27563", category: "brown" },
  { id: "M15", name: "MARD M15", hex: "#747D7A", category: "grayscale" },
];
export const MARD_COLOR_COUNT = MARD_EXTENDED_PALETTE.length;
export const UI_CATEGORY_LABELS: { id: UiColorFilter; label: string; dataCategory: MardColorCategory }[] = [
  { id: "reds", label: "Reds", dataCategory: "red" },
  { id: "blues", label: "Blues", dataCategory: "blue" },
  { id: "greens", label: "Greens", dataCategory: "green" },
  { id: "yellows", label: "Yellows", dataCategory: "yellow" },
  { id: "browns", label: "Browns", dataCategory: "brown" },
  { id: "grayscale", label: "Grayscale", dataCategory: "grayscale" },
];
function hexToRgb(hex: string) {
  const h = hex.replace("#", "");
  return { r: parseInt(h.slice(0, 2), 16), g: parseInt(h.slice(2, 4), 16), b: parseInt(h.slice(4, 6), 16) };
}
export type MardRgbEntry = { id: string; hex: string; r: number; g: number; b: number; category: MardColorCategory; hue: number };
function hexToHue(hex: string): number {
  const { r, g, b } = hexToRgb(hex);
  const rn = r / 255, gn = g / 255, bn = b / 255;
  const max = Math.max(rn, gn, bn), min = Math.min(rn, gn, bn);
  if (max === min) return 0;
  const d = max - min;
  if (max === rn) return ((gn - bn) / d + (gn < bn ? 6 : 0)) * 60;
  if (max === gn) return ((bn - rn) / d + 2) * 60;
  return ((rn - gn) / d + 4) * 60;
}
export const MARD_RGB_CACHE: MardRgbEntry[] = MARD_EXTENDED_PALETTE.map((c) => {
  const { r, g, b } = hexToRgb(c.hex);
  return { id: c.id, hex: c.hex, r, g, b, category: c.category, hue: hexToHue(c.hex) };
});
export const MARD_HEX_BY_ID: Record<string, string> = Object.fromEntries(
  MARD_EXTENDED_PALETTE.map((c) => [c.id, c.hex])
);
export const MARD_IDS_BY_DATA_CATEGORY: Record<MardColorCategory, string[]> = {
  red: [], blue: [], green: [], yellow: [], brown: [], grayscale: [],
};
for (const entry of MARD_EXTENDED_PALETTE) {
  MARD_IDS_BY_DATA_CATEGORY[entry.category].push(entry.id);
}
export function getMardHex(colorId: string): string | undefined {
  if (!colorId || typeof colorId !== "string") return undefined;
  return MARD_HEX_BY_ID[colorId];
}
export function getIdsForUiFilter(filter: UiColorFilter): string[] {
  const match = UI_CATEGORY_LABELS.find((c) => c.id === filter);
  return match ? MARD_IDS_BY_DATA_CATEGORY[match.dataCategory] : [];
}

export const MARD_RGB_BY_ID: Map<string, MardRgbEntry> = new Map(
  MARD_RGB_CACHE.map((entry) => [entry.id, entry])
);

export function getRgbEntry(colorId: string): MardRgbEntry | undefined {
  if (!colorId || typeof colorId !== "string") return undefined;
  return MARD_RGB_BY_ID.get(colorId);
}
